// <auto-generated />
using System;
using DocGenerator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocGenerator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DocGeneratorDbContext))]
    [Migration("20260804071429_AddTokenVersion")]
    partial class AddTokenVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DocGenerator.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount2Numeric")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("Amount2Words")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountNumeric")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("AmountWords")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Applicant")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaraetDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaraetNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaraetRegDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaraetRegNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerAddress")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerAddressType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerBirth")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerFamily")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerFather")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerMother")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerNationalId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerRegister")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CollectedAmount")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("ContractDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractTypeSelector")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Court")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency2")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecStatus")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecSubStatus")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileIncoming")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileIncomingDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileYear")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullData")
                        .HasColumnType("text");

                    b.Property<string>("ImmediateActions")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InclusionAmountNumeric")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("InclusionAmountWords")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InclusionCurrency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InclusionText")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lawyer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrintCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchText")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeizureDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TarithDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TarithNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TarithRegDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TarithRegNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnderFilingNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DocumentType");

                    b.HasIndex("SearchText");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.DocumentRegistrationDate", b =>
                {
                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId");

                    b.ToTable("DocumentRegistrationDates", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.ExecutionAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReminderColor")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReminderDuration")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DocumentId");

                    b.ToTable("ExecutionActions", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Guarantor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuarantorAddress")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuarantorBirth")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuarantorFamily")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuarantorFather")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuarantorMother")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuarantorName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuarantorNationalId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("GuarantorNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuarantorRegister")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Guarantors", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.LoginAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.ToTable("LoginAttempts", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.RealEstate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LandRegistry")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Property")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyDistrict")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShareType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("RealEstates", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Document", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Branch", "Branch")
                        .WithMany("Documents")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DocGenerator.Domain.Entities.User", "CreatedBy")
                        .WithMany("Documents")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.DocumentRegistrationDate", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithOne("RegistrationDate")
                        .HasForeignKey("DocGenerator.Domain.Entities.DocumentRegistrationDate", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.ExecutionAction", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithMany("ExecutionActions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Guarantor", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithMany("Guarantors")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.RealEstate", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithMany("RealEstates")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.User", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Document", b =>
                {
                    b.Navigation("ExecutionActions");

                    b.Navigation("Guarantors");

                    b.Navigation("RealEstates");

                    b.Navigation("RegistrationDate");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.User", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
