// <auto-generated />
using System;
using DocGenerator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocGenerator.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DocGeneratorDbContext))]
    [Migration("20260811195612_AddFileReceiptNumber")]
    partial class AddFileReceiptNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("DocGenerator.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount2Numeric")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("Amount2Words")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount3Numeric")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("Amount3Words")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountNumeric")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("AmountWords")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Applicant")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaraetDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaraetNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaraetRegDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaraetRegNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerAddress")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerAddressType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerBirth")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerFamily")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerFather")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerMother")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerNationalId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerRegister")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CollectedAmount")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("ContractDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractTypeSelector")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Court")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency2")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency3")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecStatus")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecSubStatus")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutedDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExecutedPaidAmount")
                        .HasColumnType("decimal(20,2)");

                    b.Property<decimal?>("ExecutedRequiredAmount")
                        .HasColumnType("decimal(20,2)");

                    b.Property<decimal?>("ExecutedRequiredAmount2")
                        .HasColumnType("decimal(20,2)");

                    b.Property<decimal?>("ExecutedRequiredAmount3")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("ExecutedRequiredCurrency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutedRequiredCurrency2")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutedRequiredCurrency3")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutedStatus")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileIncoming")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileIncomingDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FileReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileReceiptNumber")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileYear")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullData")
                        .HasColumnType("text");

                    b.Property<string>("GeneralEntitySide")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImmediateActions")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InclusionAmount2Numeric")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("InclusionAmount2Words")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InclusionAmount3Numeric")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("InclusionAmount3Words")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InclusionAmountNumeric")
                        .HasColumnType("decimal(20,2)");

                    b.Property<string>("InclusionAmountWords")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InclusionCurrency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InclusionCurrency2")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InclusionCurrency3")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InclusionText")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lawyer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrintCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReferredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferredFromLawyer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchText")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeizureDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StruckOffDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TarithDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TarithNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TarithRegDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TarithRegNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnderFilingNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DocumentType");

                    b.HasIndex("ExecutedStatus");

                    b.HasIndex("GeneralEntitySide");

                    b.HasIndex("SearchText");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.DocumentBaseNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentId", "Year")
                        .IsUnique();

                    b.ToTable("DocumentBaseNumbers", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.DocumentRegistrationDate", b =>
                {
                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateParsed")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("DateParsed");

                    b.ToTable("DocumentRegistrationDates", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.ExecutedHeir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExecutedNaturalPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExecutionApplicantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeirAddress")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeirFamily")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeirFather")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeirName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ExecutedNaturalPersonId");

                    b.HasIndex("ExecutionApplicantId");

                    b.ToTable("ExecutedHeirs", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.ExecutedNaturalPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressOrRepresentative")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressType")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeceasedFamily")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeceasedFather")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeceasedName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Family")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Father")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepresentationType")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("ExecutedNaturalPersons", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.ExecutedPublicEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityBranch")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("ExecutedPublicEntities", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.ExecutionAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionDate")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReminderColor")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReminderDuration")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DocumentId");

                    b.ToTable("ExecutionActions", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.ExecutionApplicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeceasedFamily")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeceasedFather")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeceasedName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Family")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Father")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalRepresentative")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepresentationType")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("ExecutionApplicants", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Guarantor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuarantorAddress")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuarantorBirth")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuarantorFamily")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuarantorFather")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuarantorMother")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuarantorName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuarantorNationalId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("GuarantorNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuarantorRegister")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Guarantors", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.HeadAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetLawyerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DocumentId");

                    b.HasIndex("TargetLawyerId");

                    b.ToTable("HeadAlerts", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.HeadAlertRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeadAlertId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HeadAlertId");

                    b.HasIndex("UserId");

                    b.ToTable("HeadAlertRecipients", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Heir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GuarantorNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeirAddress")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeirFamily")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeirFather")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeirName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Heirs", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.LoginAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.ToTable("LoginAttempts", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.RealEstate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LandRegistry")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Property")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyDistrict")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShareType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("RealEstates", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.RealEstateOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RealEstateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RealEstateId");

                    b.ToTable("RealEstateOwners", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("\"BranchId\" IS NULL");

                    b.HasIndex("Username", "BranchId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Document", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Branch", "Branch")
                        .WithMany("Documents")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DocGenerator.Domain.Entities.User", "CreatedBy")
                        .WithMany("Documents")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.DocumentBaseNumber", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithMany("BaseNumbers")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.DocumentRegistrationDate", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithOne("RegistrationDate")
                        .HasForeignKey("DocGenerator.Domain.Entities.DocumentRegistrationDate", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.ExecutedHeir", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithMany("ExecutedHeirs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocGenerator.Domain.Entities.ExecutedNaturalPerson", "ExecutedNaturalPerson")
                        .WithMany("Heirs")
                        .HasForeignKey("ExecutedNaturalPersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DocGenerator.Domain.Entities.ExecutionApplicant", "ExecutionApplicant")
                        .WithMany("Heirs")
                        .HasForeignKey("ExecutionApplicantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Document");

                    b.Navigation("ExecutedNaturalPerson");

                    b.Navigation("ExecutionApplicant");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.ExecutedNaturalPerson", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithMany("ExecutedNaturalPersons")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.ExecutedPublicEntity", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithMany("ExecutedPublicEntities")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.ExecutionAction", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithMany("ExecutionActions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.ExecutionApplicant", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithMany("ExecutionApplicants")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Guarantor", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithMany("Guarantors")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.HeadAlert", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocGenerator.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DocGenerator.Domain.Entities.User", "TargetLawyer")
                        .WithMany()
                        .HasForeignKey("TargetLawyerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("CreatedBy");

                    b.Navigation("Document");

                    b.Navigation("TargetLawyer");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.HeadAlertRecipient", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.HeadAlert", "HeadAlert")
                        .WithMany("Recipients")
                        .HasForeignKey("HeadAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocGenerator.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeadAlert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Heir", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithMany("Heirs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.RealEstate", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Document", "Document")
                        .WithMany("RealEstates")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.RealEstateOwner", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.RealEstate", "RealEstate")
                        .WithMany("Owners")
                        .HasForeignKey("RealEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealEstate");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.User", b =>
                {
                    b.HasOne("DocGenerator.Domain.Entities.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.Document", b =>
                {
                    b.Navigation("BaseNumbers");

                    b.Navigation("ExecutedHeirs");

                    b.Navigation("ExecutedNaturalPersons");

                    b.Navigation("ExecutedPublicEntities");

                    b.Navigation("ExecutionActions");

                    b.Navigation("ExecutionApplicants");

                    b.Navigation("Guarantors");

                    b.Navigation("Heirs");

                    b.Navigation("RealEstates");

                    b.Navigation("RegistrationDate");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.ExecutedNaturalPerson", b =>
                {
                    b.Navigation("Heirs");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.ExecutionApplicant", b =>
                {
                    b.Navigation("Heirs");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.HeadAlert", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.RealEstate", b =>
                {
                    b.Navigation("Owners");
                });

            modelBuilder.Entity("DocGenerator.Domain.Entities.User", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
