START TRANSACTION;
CREATE TABLE "IdempotencyKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" character varying(100) NOT NULL,
    "Operation" character varying(100) NOT NULL,
    "UserId" integer NOT NULL,
    "Fingerprint" character varying(64) NOT NULL,
    "ResponseBody" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_IdempotencyKeys" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_IdempotencyKeys_ExpiresAt" ON "IdempotencyKeys" ("ExpiresAt");

CREATE UNIQUE INDEX "IX_IdempotencyKeys_Key_Operation_UserId" ON "IdempotencyKeys" ("Key", "Operation", "UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261002172031_RF011_IdempotencyKeysPg', '10.0.10');

COMMIT;

