START TRANSACTION;
DROP INDEX "IX_Users_BranchId";

ALTER TABLE "Users" DROP CONSTRAINT "CK_Users_BranchRequiredForBranchRoles";

ALTER TABLE "Users" ADD "CreatedById" integer;

ALTER TABLE "Users" ADD "SectionId" integer;

ALTER TABLE "ReviewLetters" ADD "RecipientSectionId" integer;

ALTER TABLE "ExecutionCircuits" ADD "SectionId" integer;

ALTER TABLE "DocumentDelegations" ADD "RedirectedToSectionId" integer;

ALTER TABLE "DocumentDelegations" ADD "RejectReason" character varying(1000);

ALTER TABLE "DocumentDelegations" ADD "Version" bigint NOT NULL DEFAULT 0;

ALTER TABLE "DocumentAppeals" ADD "ForwardReason" character varying(1000);

ALTER TABLE "DocumentAppeals" ADD "ForwardState" character varying(20) NOT NULL DEFAULT 'Owned';

ALTER TABLE "DocumentAppeals" ADD "ForwardedAt" timestamp with time zone;

ALTER TABLE "DocumentAppeals" ADD "ForwardedById" integer;

ALTER TABLE "DocumentAppeals" ADD "Version" bigint NOT NULL DEFAULT 0;

ALTER TABLE "Correspondences" ADD "RecipientSectionId" integer;

UPDATE "DocumentAppeals" SET "Version" = 1

UPDATE "DocumentDelegations" SET "Version" = 1

CREATE TABLE "Sections" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BranchId" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "NameNorm" character varying(200) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Sections" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sections_Branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES "Branches" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "HeadSuccessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BranchId" integer NOT NULL,
    "SectionId" integer,
    "UserId" integer NOT NULL,
    "Role" character varying(20) NOT NULL,
    "Event" character varying(50) NOT NULL,
    "At" timestamp with time zone NOT NULL,
    "ActorName" character varying(200),
    "Reason" character varying(1000),
    CONSTRAINT "PK_HeadSuccessions" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_HeadSuccessions_Event" CHECK ("Event" IN ('appointed', 'deactivated', 'succeeded', 'circuit-transferred', 'renamed')),
    CONSTRAINT "FK_HeadSuccessions_Branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES "Branches" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_HeadSuccessions_Sections_SectionId" FOREIGN KEY ("SectionId") REFERENCES "Sections" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_HeadSuccessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_Users_BranchId" ON "Users" ("BranchId") WHERE "Role" = 'Head' AND "IsActive";

CREATE INDEX "IX_Users_CreatedById" ON "Users" ("CreatedById");

CREATE UNIQUE INDEX "IX_Users_SectionId" ON "Users" ("SectionId") WHERE "Role" = 'SubHead' AND "IsActive";

ALTER TABLE "Users" ADD CONSTRAINT "CK_Users_BranchRequiredForBranchRoles" CHECK ("BranchId" IS NOT NULL OR "Role" NOT IN ('Lawyer', 'Head', 'SubHead'));

CREATE INDEX "IX_ReviewLetters_RecipientSectionId" ON "ReviewLetters" ("RecipientSectionId");

CREATE INDEX "IX_ExecutionCircuits_SectionId" ON "ExecutionCircuits" ("SectionId");

CREATE INDEX "IX_DocumentDelegations_RedirectedToSectionId" ON "DocumentDelegations" ("RedirectedToSectionId");

CREATE INDEX "IX_DocumentAppeals_ForwardedById" ON "DocumentAppeals" ("ForwardedById");

CREATE INDEX "IX_DocumentAppeals_ForwardState" ON "DocumentAppeals" ("ForwardState");

ALTER TABLE "DocumentAppeals" ADD CONSTRAINT "CK_DocumentAppeals_ForwardState" CHECK ("ForwardState" IN ('Owned', 'ForwardedToHead'));

CREATE INDEX "IX_Correspondences_RecipientSectionId" ON "Correspondences" ("RecipientSectionId");

CREATE INDEX "IX_HeadSuccessions_At" ON "HeadSuccessions" ("At");

CREATE INDEX "IX_HeadSuccessions_BranchId" ON "HeadSuccessions" ("BranchId");

CREATE INDEX "IX_HeadSuccessions_SectionId" ON "HeadSuccessions" ("SectionId");

CREATE INDEX "IX_HeadSuccessions_UserId" ON "HeadSuccessions" ("UserId");

CREATE INDEX "IX_Sections_BranchId" ON "Sections" ("BranchId");

CREATE UNIQUE INDEX "IX_Sections_BranchId_NameNorm" ON "Sections" ("BranchId", "NameNorm");

CREATE INDEX "IX_Sections_IsActive" ON "Sections" ("IsActive");

ALTER TABLE "Correspondences" ADD CONSTRAINT "FK_Correspondences_Sections_RecipientSectionId" FOREIGN KEY ("RecipientSectionId") REFERENCES "Sections" ("Id") ON DELETE RESTRICT;

ALTER TABLE "DocumentDelegations" ADD CONSTRAINT "FK_DocumentDelegations_Sections_RedirectedToSectionId" FOREIGN KEY ("RedirectedToSectionId") REFERENCES "Sections" ("Id") ON DELETE RESTRICT;

ALTER TABLE "ExecutionCircuits" ADD CONSTRAINT "FK_ExecutionCircuits_Sections_SectionId" FOREIGN KEY ("SectionId") REFERENCES "Sections" ("Id") ON DELETE RESTRICT;

ALTER TABLE "ReviewLetters" ADD CONSTRAINT "FK_ReviewLetters_Sections_RecipientSectionId" FOREIGN KEY ("RecipientSectionId") REFERENCES "Sections" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_Sections_SectionId" FOREIGN KEY ("SectionId") REFERENCES "Sections" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261006084556_AddSubHeadSections', '10.0.10');

COMMIT;

